class Translation(object):

    HELP_TEXT = """<b><u>Hᴇʀᴇ Is Tʜᴇ Hᴇʟᴘ Fᴏʀ MY Cᴏᴍᴍᴀɴᴅs</u></b>\n\n • /start :- Cʜᴇᴄᴋ Iᴀᴍ Aʟɪᴠᴇ\n • /help :- Mᴏʀᴇ Dᴇᴛᴀɪʟs\n • /about :- Aʙᴏᴜᴛ Mᴇ\n • /sub :- Sᴜᴘᴘᴏʀᴛ ᴀɴᴅ ᴅᴇᴘʟᴏʏ\n • /stats :- Usᴇʀ Cᴏᴜɴᴛ""" 
    START_TEXT =  """Hᴇʟᴏ {},
Mʏ Nᴀᴍᴇ Is <a href='http://t.me/JerryV3Bot'>ᴊᴇʀʀʏ</a>, I Cᴀɴ Pʀᴏᴠɪᴅᴇ Mᴏᴠɪᴇs, Jᴜsᴛ Aᴅᴅ Mᴇ Tᴏ Yᴏᴜʀ Gʀᴏᴜᴘ Aɴᴅ Eɴᴊᴏʏ 🐭"""
    ABOUT_TEXT = """✯ Mʏ Nᴀᴍᴇ: ᴊᴇʀʀʏ
✯ Cʀᴇᴀᴛᴏʀ: <a href=https://t.me/VAMPIRE_KING_NO_1>ƬЄƦƦƠƦ MƖƇƘЄƳ</a>
✯ Lɪʙʀᴀʀʏ: Pʏʀᴏɢʀᴀᴍ
✯ Lᴀɴɢᴜᴀɢᴇ: Pʏᴛʜᴏɴ 3 
✯ Dᴀᴛᴀ Bᴀsᴇ: ᴍᴏɴɢᴏ ᴅʙ
✯ ⲂⲞⲦ SᴇʀᴠᴇʀꞄ: Hᴇʀᴏᴋᴜ
✯ Bᴜɪʟᴅ Sᴛᴀᴛᴜs: v1.0.1 [ Bᴇᴛᴀ ]"""
    FSUB_TEXT = """ഹേയ് {} തായേ കാണുന്ന ചാനലിൽ നിങ്ങൾ ഇല്ല അത് കൊണ്ട് നിങ്ങൾക് സിനിമ കിട്ടില്ല...\nസിനിമ കിട്ടാനായി താഴെ കാണുന്ന 🔔 Join എന്ന ബട്ടനിൽ ക്ലിക്ക് ചെയ്തു ഞങ്ങളുടെ മെയിൻ ചാനലിൽ ജോയിൻ ചെയ്യുക എങ്കിൽ മാത്രമേ നിങ്ങൾക്ക് മൂവി ഈ ബോട്ട് വഴി ലഭിക്കുകയുള്ളു. അതു കഴ്ഞ്ഞു തായേ കാണുന്ന 👉"Try again"👈 എന്നുള്ളതിൽ ക്ലിക്ക് ചെയ്തു Start കൊടുത്താൽ നിങ്ങൾക്ക് മൂവി കിട്ടുന്നതാണ്...😁😁"""
    FILTER_TEXT = """<b><u>Mᴀɴᴜᴀʟ Fɪʟᴛᴇʀ</u></b>\n\n• Aᴅᴅ ᴍᴇ ᴀs ᴀᴅᴍɪɴ ɪɴ ʏᴏᴜʀ ɢʀᴏᴜᴘ ᴀɴᴅ sᴛᴀʀᴛ ғɪʟᴛᴇʀɪɴɢ:\n\n<b><u>NOTE:</u></b>\n\n1. ᴊᴇʀʀʏ sʜᴏᴜʟᴅ ʜᴀᴠᴇ ᴀᴅᴍɪɴ ᴘʀɪᴠɪʟʟᴀɢᴇ.\n2. ᴏɴʟʏ ᴀᴅᴍɪɴs ᴄᴀɴ ᴀᴅᴅ ғɪʟᴛᴇʀs ɪɴ ᴀ ᴄʜᴀᴛ.\n3. ᴀʟᴇʀᴛ ʙᴜᴛᴛᴏɴs ʜᴀᴠᴇ ᴀ ʟɪᴍɪᴛ ᴏғ 64 ᴄʜᴀʀᴀᴄᴛᴇʀs.\n\n<b><u>Cᴏᴍᴍᴀɴᴅs ᴀɴᴅ Usᴀɢᴇ:</u></b>\n• /addfilter - Aᴅᴅ ғɪʟᴛᴇʀ ғᴏʀ ɴᴀᴍᴇ\n• /filters - Lɪsᴛ ᴀʟʟ ғɪʟᴛᴇʀs ɪɴ ᴄʜᴀᴛ\n• /delfilters - Dᴇʟᴇᴛᴇ ғɪʟᴛᴇʀ\n• /delallfilters - Dᴇʟᴇᴛᴇ ᴇɴᴛɪʀᴇ ғɪʟᴛᴇʀs (Gʀᴏᴜᴘ Oᴡɴᴇʀ Oɴʟʏ!)"""
    AUTOFILTER_TEXT = """<b><u>Aᴜᴛᴏ Fɪʟᴛᴇʀ</u></b>\n\n<b><u>Cᴏᴍᴍᴀɴᴅs</u></b>\n  <code>(Wᴏʀᴋs Oɴʟʏ Iɴ Gʀᴏᴜᴘs):</code>\n\n<b><u>Aᴅᴅ CMD</u></b>\n  ☞ <code>/addchannel</code> <b>chat_id</b>\n  ☞ <code>/addchannel</code> <b>```@TV_SeriesCourt```</b>\n<b>- Tᴏ Cᴏɴɴᴇᴄᴛ A Gʀᴏᴜᴘ Wɪᴛʜ A Cʜᴀɴɴᴇʟ (Bᴏᴛ Sʜᴏᴜʟᴅ Bᴇ Aᴅᴍɪɴ Wɪᴛʜ Fᴜʟʟ Pʀᴇᴠɪʟᴀɢᴇs Iɴ Bᴏᴛʜ Gʀᴏᴜᴘ Aɴᴅ Cʜᴀɴɴᴇʟ)</b>\n\n<b><u>Dᴇʟᴇᴛᴇᴅ CMD</u></b>\n  ☞ <code>/delchannel</code> <b>chat_id</b>\n  ☞ <code>/delchannel</code> <b>```@TV_SeriesCourt```</b>\n<b>- Tᴏ ᴅɪsᴄᴏɴɴᴇᴄᴛ A Gʀᴏᴜᴘ Wɪᴛʜ A Cʜᴀɴɴᴇʟ</i></b>"""
    AUTOFILTER_TEXT2 = """<b><u>ᴍᴀɪɴ ɪɴғᴏʀᴍᴀᴛɪᴏɴ</u></b>\n\n  ☞ <b>/settings</b> -  <b>Tʜɪs Cᴏᴍᴍᴀɴᴅ Wɪʟʟ Dɪsᴘʟᴀʏ Yᴏᴜ A Sᴇᴛᴛɪɴɢs Pᴀɴɴᴇʟ Iɴsᴛᴀɴᴄᴇ Wʜɪᴄʜ Cᴀɴ Bᴇ Usᴇᴅ Tᴏ Tᴡᴇᴇᴋ Bᴏᴛ's Sᴇᴛᴛɪɴɢs Aᴄᴄᴏʀᴅɪɴɢʟʏ</b>\n\n  ☞ <b>Cʜᴀɴɴᴇʟ</b> - <b>Bᴜᴛᴛᴏɴ Wɪʟʟ Sʜᴏᴡ Yᴏᴜ Aʟʟ Tʜᴇ Cᴏɴɴᴇᴄᴛᴇᴅ Cʜᴀᴛs Wɪᴛʜ Tʜᴇ Gʀᴏᴜᴘ Aɴᴅ Wɪʟʟ Sʜᴏᴡ Bᴜᴛᴛᴏɴs Cᴏʀʀᴇsᴘɴᴅɪɴɢ Tᴏ Tʜᴇʀᴇ Oʀᴅᴇʀ Fᴏʀ Fᴜʀᴛʜᴜʀ Cᴏɴᴛʀᴏʟs</b>\n\n  ☞ <b>Fɪʟᴛᴇʀ Tʏᴘᴇs</b> - <b>Bᴜᴛᴛᴏɴ Wɪʟʟ Sʜᴏᴡ Yᴏᴜ Tʜᴇ 3 Fɪʟᴛᴇʀ Oᴘᴛɪᴏɴ Aᴠᴀɪʟᴀʙʟᴇ Iɴ Bᴏᴛ... Pʀᴇssɪɴɢ Eᴀᴄʜ Bᴜᴛᴛᴏɴs Wɪʟʟ Eɪᴛʜᴇʀ Eɴᴀʙʟᴇ ᴏʀ Dɪsᴀʙʟᴇ Tʜᴇᴍ Aɴᴅ Tʜɪs Wɪʟʟ Tᴀᴋᴇ Iɴᴛᴏ Aᴄᴛɪᴏɴ As Sᴏᴏɴ As Yᴏᴜ Usᴇ Tʜᴇᴍ Wɪᴛʜᴏᴜᴛ Tʜᴇ Nᴇᴇᴅ Oғ A Rᴇsᴛᴀʀᴛ</b>      \n\n  ☞ <b>Configure</b> - <b>Bᴜᴛᴛᴏɴ Wɪʟʟ Hᴇʟᴘs Yᴏᴜ Tᴏ Cʜᴀɴɢᴇ Nᴏ. ᴏғ Pᴀɢᴇs/ Bᴜᴛᴛᴏɴs Pᴇʀ Pᴀɢᴇ/ Tᴏᴛᴀʟ Rᴇsᴜʟᴛ Wɪᴛʜᴏᴜᴛ Aᴄᴜᴛᴀʟʟʏ Eᴅɪᴛɪɴɢ Tʜᴇ Rᴇᴘᴏ... Aʟsᴏ Iᴛ Pʀᴏᴠɪᴅᴇ Oᴘᴛɪᴏɴ Tᴏ Eɴᴀʙʟᴇ/Dɪsᴀʙʟᴇ Fᴏʀ Sʜᴏᴡɪɴɢ Iɴᴠɪᴛᴇ Lɪɴᴋ Iɴ Eᴀᴄʜ Rᴇsᴜʟᴛs</b>"""
    DYNO_TEXT = """👤Total Users {}\n🧐Total Chtas {}\n🤯Total Manul Filters {}\n🕐Bot Update Time {}"""
    INFORMATION_TEXT = """<b><u>Extra Modes</u></b>\n\n<b>NOTE:</b>\nthese are the extra features of Donlee Robot v2\n\n<b><u>Work Only Group:</u></b>:\n\n• No inline Message\n• No Forword Message\n\n<b><u>CMD Work Only Group:</u></b>\n• /report - report To admin\n\n<b><u>Commands and Usage:</u></b>\n• /id - get id about a user and group.\n• /info  - get information about a user and Group.\n• /status - Get Bot Status"""
    CREDITS_TEXT = """<u><b>DEV</b></u>\n• Muhammed RK\n\n<b><u>TroJanzHEX</u></b>\n• Unlimitedfilter\n<b><u>CrazyBotsz</u></b>\n• ADV AutoFilter V2\n<b><u>Bughunter</u></b>\n• Report\n• Ban\n<b><u>Professor-99</u></b>\n• Broadcast Bot\n• DonLee Robot 2.9 IMDB poster\n• Forword and Inline Delete\n• unban\n• [Refresh Button] Donlee Robot\n<b><u>EvamariaTG</u></b>\n• Evamaria IMDB Poster"""
    CONNECTION_TEXT = """<b><u>Connection</u></b>\n\n- Used to connect bot to PM for managing filters \n- it helps to avoid spamming in groups.\n\nNOTE:\n1. Only admins can add a connection.\n2. Send /connect for connecting me to ur PM\n\nCommands and Usage:\n• /connect  - connect a particular chat to your PM\n• /disconnect  - disconnect from a chat\n• /connections - list all your connections"""
    DEV_TEXT = """<b><u>DEVELOPER INFO</b></u>\n\n• TG Name : <a href="t.me/Mrk_yt">Muhammed</a>\n• TG Username : <a href="t.me/Mrk_yt">@MRK_YT</a>\n• Github : <a href="https://github.com/PR0FESS0R-99/PR0FESS0R-99">Pr0fess0r-99</a>\n• Insta :  <a href="https://www.instagram.com/mrk_yt_">Mrk_YT_</a> \n• YouTube : <a href="https://youtube.com/c/MoTech_YT">Mo Tech</a> \n• Whatsapp : None\n• Facebook : Mrk-YT"""
    GROUP_ADMIN_TEXT = """<b><u>Group Commands</u></b>\n\n<b><u>Bot Master</u></b>\n• /broadcast - Replay Any Message\n\n<b><u>Group Admin Only</u></b>\n• /ban - Reply Any User Text\n• /unban - Reply Banned User Text"""
    SUB_TEXT = """JOIN, SHARE, MAXIMUM SUPPORT"""
    SPELLING_TEXT = """Hey {} Check Your Spelling"""
    STATUS_TEXT = """<b><u>Bot Status</u></b>\nTotal Users <b>{}</b>"""
    SOURCE_TEXT = """<b><u>🥳 DONLEE SOURCE CODE</b></u>\n\n📦 REPOSITORY :- https://github.com/PR0FESS0R-99/DonLee-Robot-V2\n📺 DEPLOY VIDEO :- https://youtu.be/NrbMc93aCzA\n\n👩‍👩‍👧‍👧 DEVELOPER TEAM <a href="https://t.me/Mo_Tech_YT">Mo Tech</a>"""
